export const Steps = {
  INPUT_NAME_STRING: "INPUT_NAME_STRING",
  INPUT_CLASSNAME: "INPUT_CLASSNAME",
  DONT_KNOW: "DONT_KNOW",
  WARRIOR_WEAPON_CHOICE: "WARRIOR_WEAPON_CHOICE",
  MAGE_WEAPON_CHOICE: "MAGE_WEAPON_CHOICE",
};
